version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "1234:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=1234    
      - PORT=3000
    stdin_open: true
    tty: true